#!/bin/bash 
echo "This script will delete .log .dat .rst file and all working dir."

read -p "Are you sure? (y/n) (Type L or l for the list of deleted files)" -n 1 -r

if [[ $REPLY =~ ^[Ll]$ ]]
then
    echo -----------Directories-------------
    ls | grep workdir
    echo -------------.dat------------------
    ls | grep "\.dat"
    echo -------------.log------------------
    ls | grep "\.log"
    echo -------------.rst------------------
    ls | grep "\.rst"
    echo -----------------------------------
    read -p "Are you sure? (y/n)" -n 1 -r
fi


if [[ $REPLY =~ ^[Yy]$ ]]
then
    rm -r workdir.* & rm *\.dat *\.log *\.rst
fi

exit 1
